
-- Verifying field types and column names of each table --

DESCRIBE NorthwindTraders.categories;
DESCRIBE NorthwindTraders.customers;
DESCRIBE NorthwindTraders.employees;
DESCRIBE NorthwindTraders.order_details;
DESCRIBE NorthwindTraders.orders;
DESCRIBE NorthwindTraders.products;
DESCRIBE NorthwindTraders.shippers;

--
-- Verifying data integrity of each table -- 

SELECT * FROM NorthwindTraders.categories;
SELECT * FROM NorthwindTraders.customers;
SELECT * FROM NorthwindTraders.employees;
SELECT * FROM NorthwindTraders.order_details;
SELECT * FROM NorthwindTraders.orders;
SELECT * FROM NorthwindTraders.products;
SELECT * FROM NorthwindTraders.shippers;

--

SET SQL_SAFE_UPDATES = 0;
SET sql_mode = '';

-- Handling Missing Values -- 

-- Orders Table --
SELECT * FROM NorthwindTraders.orders 
WHERE shippedDate = "";

UPDATE NorthwindTraders.orders -- Setting missing values as NULL
SET shippedDate = NULL
WHERE shippedDate = "";

-- Employee Table --
SELECT * FROM NorthwindTraders.employees
WHERE reportsTo = "";

UPDATE NorthwindTraders.employees -- Setting missing values as NULL
SET reportsTo = NULL
WHERE reportsTo = "";

--
-- Changing Date Format in the Orders table --

ALTER TABLE NorthwindTraders.orders 
MODIFY orderDate VARCHAR(20); 

UPDATE NorthwindTraders.orders 
SET orderDate = DATE_FORMAT(STR_TO_DATE(orderDate, '%Y-%m-%d'), '%Y-%m-%d');

ALTER TABLE NorthwindTraders.orders 
MODIFY orderDate DATETIME;

--

ALTER TABLE NorthwindTraders.orders 
MODIFY requiredDate VARCHAR(20); 

UPDATE NorthwindTraders.orders 
SET requiredDate = DATE_FORMAT(STR_TO_DATE(requiredDate, '%Y-%m-%d'), '%Y-%m-%d');

ALTER TABLE NorthwindTraders.orders 
MODIFY requiredDate DATETIME;

-- 

ALTER TABLE NorthwindTraders.orders 
MODIFY shippedDate VARCHAR(20); 

UPDATE NorthwindTraders.orders 
SET shippedDate = DATE_FORMAT(STR_TO_DATE(shippedDate, '%Y-%m-%d'), '%Y-%m-%d')
WHERE shippedDate IS NOT NULL;

ALTER TABLE NorthwindTraders.orders 
MODIFY shippedDate DATETIME;

-- 
-- Changing column nomenclature in Products Table --

SELECT * FROM NorthwindTraders.products
WHERE discontinued = "1";

UPDATE NorthwindTraders.products
SET discontinued = "Yes"
WHERE discontinued = "1";

SELECT * FROM NorthwindTraders.products
WHERE discontinued = "0";

UPDATE NorthwindTraders.products
SET discontinued = "No"
WHERE discontinued = "0";

--
-- DATA EXPLORATION --

SELECT * FROM NorthwindTraders.order_details;

SELECT COUNT(orderID) FROM NorthwindTraders.orders; -- There are 830 unique orders 
SELECT COUNT(DISTINCT customerID) FROM orders; -- There are 89 unique customers 
SELECT COUNT(DISTINCT categoryID) FROM products; -- There are 8 unique categories

SELECT ROUND(SUM(unitPrice * quantity * (1 - discount)),2) AS TotalRevenue  -- Total revenue generated
FROM order_details;

SELECT orderID, ROUND(SUM(unitPrice * quantity * (1 - discount)),2) AS orderRevenue  -- Total revenue generated per order 
FROM order_details
GROUP BY orderID
ORDER BY orderID; -- orderRevenue DESC

SELECT productID, ROUND(SUM(unitPrice * quantity * (1 - discount)),2) AS productRevenue -- Total revenue generated per product 
FROM order_details 
GROUP BY productID
ORDER BY productId; -- productRevenue DESC 

SELECT ca.categoryID, od.productID, od.quantity,od.orderID,
od.unitPrice * od.quantity * (1 - od.discount) AS productRevenue,
SUM(od.unitPrice * od.quantity * (1 - od.discount))  OVER (PARTITION BY ca.categoryID) AS categoryRevenue -- Total revenue generated by category V1
FROM order_details as od
JOIN products AS p
ON od.productID = p.productID
JOIN categories as ca
ON p.categoryID = ca.categoryID 
ORDER BY ca.categoryID, od.productID;

SELECT ca.categoryID, ROUND(SUM(od.unitPrice * od.quantity * (1 - od.discount)),2) AS categoryRevenue -- Total revenue generated by category V2
FROM order_details as od
JOIN products as p
ON od.productID = p.productID 
JOIN categories as ca
ON p.categoryID = ca.categoryID
GROUP BY ca.categoryID
ORDER BY ca.categoryID; -- categoryRevenue DESC

SELECT o.customerID, o.orderID, od.orderID, od.productID, od.quantity, od.discount, -- Total revenue generated per customer V1
od.unitPrice * od.quantity * (1 - od.discount) AS orderRevenue,
SUM(od.unitPrice * od.quantity * (1 - od.discount)) OVER (PARTITION BY o.customerID) AS customerRevenue
FROM orders AS o
JOIN order_details AS od
ON  o.orderID = od.orderID 
ORDER BY o.customerID, o.orderID; -- customerRevenue DESC

SELECT o.customerID, SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS customerRevenue -- Total revenue generated per customer V2
FROM orders AS o
JOIN order_details AS od
ON o.orderID = od.orderID 
GROUP BY o.customerID
ORDER BY o.customerID; -- customerRevenue DESC

SELECT cu.country, o.customerID, o.orderID, od.productID, od.quantity, od.discount, -- Total revenue generated by country V1
od.unitPrice * od.quantity * (1 - od.discount) AS orderRevenue,
SUM(od.unitPrice * od.quantity * (1 - od.discount)) OVER (PARTITION BY cu.country) AS countryRevenue
FROM order_details as od
JOIN orders as o
ON od.orderId = o.orderID 
JOIN customers as cu
ON cu.customerID = o.customerId
ORDER BY cu.country, o.orderID; --  countryRevenue DESC

SELECT cu.country, ROUND(SUM(od.unitPrice * od.quantity * (1 - od.discount)),2) AS countryRevenue -- Total revenue generated by country V2 
FROM order_details as od
JOIN orders as o
ON od.orderId = o.orderID 
JOIN customers as cu
ON cu.customerID = o.customerId
GROUP BY cu.country
ORDER BY cu.country; -- countryRevenue DESC

SELECT productID, COUNT(DISTINCT orderID) AS ordersPerProduct -- Total number of orders per product 
FROM NorthwindTraders.order_details
GROUP BY productID
ORDER BY productID; -- ordersPerProduct DESC

SELECT customerID, COUNT(DISTINCT orderID) as ordersPerCustomer -- Total number of orders per customer 
FROM orders
GROUP BY customerID
ORDER BY customerID; -- ordersPerCustomer DESC

SELECT p.categoryID, COUNT(DISTINCT orderID) as ordersByCategory -- Total number of orders by category
FROM order_details as od
JOIN products as p
ON od.productID = p.productID
GROUP BY p.categoryID
ORDER BY p.categoryID; -- ordersByCategory DESC

SELECT cu.country, COUNT(DISTINCT orderID) as ordersByCountry -- Total number of orders by country
FROM orders as o
JOIN customers as cu
ON o.customerID = c.customerID
GROUP BY cu.country
ORDER BY cu.country; -- ordersByCountry DESC

SELECT s.shipperID, COUNT(DISTINCT orderID) as ordersShippedByShipper -- Total number of orders shipped by shipper 
FROM orders as o
JOIN shippers as s
ON s.shipperID = o.shipperID
GROUP BY s.shipperID
ORDER BY s.shipperID; 

SELECT shipperID, ROUND(SUM(freight),2) AS totalFreightCost  -- Total freight cost by shipper
FROM orders
GROUP BY shipperID
ORDER BY shipperID;

SELECT e.employeeID, e.employeeName, e.Title, 
COUNT(DISTINCT o.orderID) as ordersPerEmployee, -- Total number of orders per employee
SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS employeeRevenue -- Total revenue generated by employee 
FROM employees AS e
JOIN orders AS o
ON e.employeeID = o.employeeID 
JOIN order_details AS od 
ON o.orderID = od.orderID
GROUP BY e.employeeID
ORDER BY e.employeeID; -- employeeRevenue DESC
